language: java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: bramhi123-github
    token:
      secure: f600635f918f0244cc2e9ba3d57d9dad8670ff27
script:
  ./gradlew clean check jacocoTestReport sonarqube build
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
